### ISSUE TITLE
Stack trace with resque

### ISSUE THREAD

**Issue by wr0ngway** [ryanlecompte/redis_failover#12]
I'm seeing the following when using redis_failover with resque (specifically from resque web ui) - I could be doing something wrong, haven't dug that deep yet.

ArgumentError - wrong number of arguments (2 for 1):
    /mnt/appleton-matt/shared/bundle/ruby/1.9.1/gems/redis_failover-0.8.1/lib/redis_failover/client.rb:127:in `respond_to_missing?'
    /mnt/appleton-matt/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.0.3/lib/redis/namespace.rb:169:in`respond_to?'
    /mnt/appleton-matt/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.0.3/lib/redis/namespace.rb:169:in `respond_to?'
    /mnt/appleton-matt/shared/bundle/ruby/1.9.1/bundler/gems/resque-fcaf987d0724/lib/resque.rb:58:in`redis_id'
    /mnt/appleton-matt/shared/bundle/ruby/1.9.1/bundler/gems/resque-fcaf987d0724/lib/resque/server/views/layout.erb:40:in `evaluate_source'

**Comment by ryanlecompte** [comment]
Yes, this is a bug in the method signature for RedisFailover::Client#respond_to_missing?. I just checked in a fix for this in master. Could you please give it a shot? I'll cut a 0.8.2 release for this soon.

**Comment by wr0ngway** [comment]
Looks like master has it fixed now (resque-web works with it), thanks.

**Comment by ryanlecompte** [comment]
Great, just released 0.8.2 for this since I think it's pretty critical. Thanks!
