### ISSUE TITLE
Feature Request: Force failover to a slave

### ISSUE THREAD

**Issue by eric** [ryanlecompte/redis_failover#2]
It would be nice to have a way to force failover to a slave so it is coordinated better than just doing a kill -9 on the master.

Seeing as redis still doesn't have a read-only flag you can set on a server, I think it would require issuing a shutdown to the old master to ensure clients don't continue to write to the master that changes to a slave (and would also provide them with a way to get notification that they need to refresh the server list).

**Comment by ryanlecompte** [comment]
I like this and definitely think it's worth adding as a feature for redis_failover.

**Comment by wr0ngway** [comment]
+1

**Comment by ryanlecompte** [comment]
Just released version 0.8 which now has manual failover support.
