### ISSUE TITLE
Discussion: Adding daemonize and log rotate signal

### ISSUE THREAD

**Issue by kyohsuke** [ryanlecompte/redis_failover#23]
Hi, Ryan.

I'm adding daemonize and logrotateing.
But, Its code seems like dirty, though.
1. use class eval
   https://github.com/kyohsuke/redis_failover/commit/a2888d41e77de89f827437801b95800bc8843905
2. use class variables
   https://github.com/kyohsuke/redis_failover/commit/8415c9911e44104e37088309fd197759367c51b7

Do you have any good idea?

Thanks

**Comment by ryanlecompte** [comment]
Usually I prefer to daemonize and log rotate outside of the core library. There are other tools out there which are great for this, e.g. monit. Thoughts?

**Comment by kyohsuke** [comment]
Sure, I think that you say, too.
But that is not an example in the libraries and wiki pages.
And If daemon puts to STDOUT, the $! will not get node manager's PID via init script.

e.g)
https://gist.github.com/531b34c2b29ab2fc42f6

It problem seems ilke that has an alternative solution.
I'm so sorry I cannot imagine other solution.
I think, you write a daemonize example via wiki, that is the best solution.

If you can write a daemonize example, please write an example and close it?

Thanks

**Comment by ryanlecompte** [comment]
Closing out this issue since the recommended approach is to manage redis_node_manager as a daemon with monit / god /etc.
