### ISSUE TITLE
FeatureRequest: Implement redis server pools

### ISSUE THREAD

**Issue by wr0ngway** [ryanlecompte/redis_failover#25]
In our cluster we have more than one redis cluster - one for app caching, etc, another for resque.  I'm about to setup node_manager servers for each of these by having a different znode_path.  However, it would be nice if I could just have a single set of node_manager servers and tell it I have multiple disparate redis clusters.

Since RedisFailover::Client takes the znode_path, which I would configure differently for connections to each pool, I think all that is left is to make node_manager be able to take a list of znode_paths and do the right thing...?

**Comment by ryanlecompte** [comment]
I think this is definitely a nice feature to have. Unfortunately for now the node manager takes an explicit list of redis servers to monitor. It would need to instead take multiple sets of znode path + redis server configuration pairs. This would be easier to do in the config.yml file than on the command-line.

**Comment by wr0ngway** [comment]
That would be fine - I generate that config file from a erb template, so thats easy to do for me :0  I just want to avoid having to run 2 sets of redis_node_manager daemons (I run multiple daemons for each redis cluster for redundancies sake)

**Comment by ryanlecompte** [comment]
After giving this some more thought, I think I want to keep a redis_node_manager as managing a single redis cluster. Trying to keep track of who is the redis master for two different clusters in a single process would make the code a bit unmanageable. The upcoming 1.0 release introduces distributed monitoring and node/failover strategies. These features depend on the existing notion of a single redis cluster being managed by a single redis_node_manager cluster.
