### ISSUE TITLE
Full Failure of server

### ISSUE THREAD

**Issue by ScotterC** [ryanlecompte/redis_failover#40]
For the situation where zookeeper, redis and a node manager are on the same server, RedisFailover can't seem to reconcile the situation of losing an entire cluster of these three.  

For example:

If I have two servers, each with an instance of redis, zookeeper and a redis_node manager with one in slave to the other and I completely kill the server with the master redis instance, the other server can't reconcile it because - I believe - it can't communicate with those zookeeper instances anymore.  If zookeeper can't be communicated with anymore, isn't the best course of action to try and mark that redis instance as unavailable and switch the slave over to master?

**Comment by ryanlecompte** [comment]
If you only have one ZK server up, you don't have quorum and failover isn't safe. It's recommended to have 5 nodes in your cluster.
