### ISSUE TITLE
Prevent reads on slaves

### ISSUE THREAD

**Issue by lloydmeta** [ryanlecompte/redis_failover#49]
Is it possible to make it so that slaves are not used for reads at all? 

I know I can set the slave-serve-stale-data setting on the slave to 'no' but I think this will involve one attempt to read from the slave, getting a reply of "SYNC with master in progress", then reading from the master. In the case, I think performance will be adversely affected.

**Comment by ryanlecompte** [comment]
There is a "master_only" option that you can set when you create your RedisFailover::Client. All reads and writes will go to the master only. This should be covered in the README, I believe.

**Comment by lloydmeta** [comment]
Ah, that's what master_only means :) sorry about that!

By the way thanks for the awesome library!

**Comment by ryanlecompte** [comment]
Cool! You're welcome. :-)
