### ISSUE TITLE
Redis-failover start up error

### ISSUE THREAD

**Issue by SureshSc** [ryanlecompte/redis_failover#72]
Hi ,
I have followed your installation guidelines and sample daemon execution (redis_node_manager -n localhost:6379,localhost:6380 -z localhost:2181,localhost:2182,localhost:2183). But i got following errors.

server:redis_failover-master suresh$ redis_node_manager -C examples/config.yml 
Sat Jan 18 11:40:08 UTC 2014 RedisFailover 42803 INFO: Redis Node Manager v1.0.2 starting (ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0])
/Library/Ruby/Gems/1.8/gems/redis_failover-1.0.2/lib/redis_failover/node_strategy.rb:14:in `for': Failed to find node strategy: majority (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/redis_failover-1.0.2/lib/redis_failover/node_manager.rb:42:in`initialize'
    from /Library/Ruby/Gems/1.8/gems/redis_failover-1.0.2/lib/redis_failover/runner.rb:11:in `new'
    from /Library/Ruby/Gems/1.8/gems/redis_failover-1.0.2/lib/redis_failover/runner.rb:11:in`run'
    from /Library/Ruby/Gems/1.8/gems/redis_failover-1.0.2/bin/redis_node_manager:6
    from /usr/bin/redis_node_manager:23:in `load'
    from /usr/bin/redis_node_manager:23

**Comment by ryanlecompte** [comment]
redis_failover doesn't officially support Ruby 1.8.7. Please upgrade to Ruby 1.9+
